apiVersion: v1
kind: Service
metadata:
  name: grpc-todo-server-service
spec:
  type: NodePort
  selector:
    app: grpc-todo-server
  ports:
  - protocol: TCP
    port: 4000       
    targetPort: 4000 
    nodePort: 30007  
    
